version: 2
jobs:
  checkout-existing:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "44:a7:27:96:24:30:76:b2:61:d3:fa:07:ec:8d:f0:5a"
      - run:
          name: Pull master
          command: |
            mkdir public && cd ./public
            git init
            git remote add origin git@github.com:shadowimmage/shadowimmage.github.io.git
            git pull origin master
            git checkout -b update

  build:
    working_directory: ~/project
    docker:
      - image: cibuilds/hugo:0.40.2
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Run Hugo
          command: HUGO_ENV=production hugo -v

  test:
    working_directory: ~/project
    docker:
      - image: cibuilds/hugo:0.40.2
    steps:
      - run:
          name: html check
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore

  deploy-master:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "44:a7:27:96:24:30:76:b2:61:d3:fa:07:ec:8d:f0:5a"
      - run:
          name: Update master with changes
          command: |
            cd ./public
            # mv ./* ../tmp
            
            # rm -r ./*
            # git add *
            # git commit -m "clean"
            # mv ../tmp/* .
            git add *
            commitMsg="CircleCI site rebuild at `date`"
            git commit -m "$commitMsg"
            git checkout -b master
            git merge update
            git push origin master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout-existing
      - build:
          requires:
            - checkout-existing
          filters:
            branches:
              only:
                - hugo
      - test:
          requires:
            - build
      - deploy-master:
          requires:
            - test